
CREATE PROCEDURE spSearchEmployeesBadDynamicSQL
@FIRSTNAME NVARCHAR(100),
@LASTNAME NVARCHAR(100),
@GENDER NVARCHAR(100),
@SALARY INT
AS
BEGIN
	DECLARE @SQL NVARCHAR(MAX)
	SET @SQL = 'SELECT * FROM EMPLOYEE_ WHERE 1 = 1'

	IF(@FIRSTNAME IS NOT NULL)
		SET @SQL = @SQL + 'AND FIRSTNAME ="' + @FIRSTNAME +  '"'
	IF(@LASTNAME IS NOT NULL)
		SET @SQL = @SQL + ' AND LASTNAME ="' + @LASTNAME +'"'
	IF(@GENDER IS NOT NULL)
		SET @SQL = @SQL + 'AND GENDER ="' + @GENDER + '"'
	IF(@SALARY IS NOT NULL)
		SET @SQL = @SQL + 'AND SALARY ="' + @SALARY + '"'

		EXECUTE sp_execute @SQL
END