USE UAT

SELECT Name,Salary,Gender,
SUM(Salary) OVER (ORDER BY ID) AS RUNNING_TOTAL
FROM Employees


SELECT Name,Salary,Gender,
SUM(Salary) OVER (PARTITION BY GENDER ORDER BY ID) AS RUNNING_TOTAL
FROM Employees


---IF YOU HAVE DUBPLICATE RECORD
--NOTE:- USER THAT COLUMN WHICH HAVE PRIMARY KEY MEANS UNIQE COLUMN

SELECT Name,Salary,Gender,
SUM(Salary) OVER (PARTITION BY GENDER ORDER BY SALARY) AS RUNNING_TOTAL
FROM Employees

