CREATE TABLE ACCOUNTS
(
	ID INT IDENTITY(1,1),
	NAME NVARCHAR(50),
	BALANCE NVARCHAR(50)
)

INSERT INTO ACCOUNTS VALUES('MARK','1000'),('MARY','1000')

SELECT * FROM ACCOUNTS

BEGIN TRY
	BEGIN TRANSACTION 
	UPDATE ACCOUNTS SET BALANCE = BALANCE - 100 WHERE ID = 1
	UPDATE ACCOUNTS SET BALANCE = BALANCE + 100 WHERE ID = 'A'
	COMMIT TRANSACTION
	PRINT 'TRANSACTION COMMITTED'
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
	PRINT 'TRANSACTION ROLLED BACK'
END CATCH 
