use UAT

SELECT ID,NAME FROM TableA
EXCEPT
SELECT ID, NAME FROM TableB

SELECT ID,NAME FROM TableA
WHERE ID NOT IN(SELECT ID FROM TableB)

--YOU SHOULD NOT MAKE QUERY LIKE THIS
-- YOU WILL GET ERROR

SELECT ID FROM TableA
EXCEPT
SELECT ID, NAME FROM TableB

SELECT ID,NAME FROM TableA
WHERE ID NOT IN(SELECT ID,NAME FROM TableB)