
SELECT EOMONTH('08/07/2020') AS RESULT

SELECT EOMONTH('08/07/2020', 2) AS RESULT

SELECT EOMONTH('08/07/2020', -1) AS RESULT

SELECT * FROM Employees_Choose

SELECT NAME,DateOfBirth, EOMONTH(DateOfBirth) AS LASTDAY
FROM Employees_Choose


SELECT NAME,DateOfBirth, DATEPART(DD, EOMONTH(DateOfBirth)) AS LASTDAY
FROM Employees_Choose