CREATE DATABASE INTERVIEW_PRACTICE

USE INTERVIEW_PRACTICE

-- HOW TO FIND N HIGHEST SALARY
CREATE TABLE tbl_Employee
(
	ID INT IDENTITY(1,1),
	FIRSTNAME VARCHAR(50),
	LASTNAME VARCHAR(50),
	GENDER VARCHAR(50),
	SALARY VARCHAR(50)
)

INSERT INTO tbl_Employee (FIRSTNAME,LASTNAME,GENDER,SALARY) 
VALUES('STEVE','POUNDS','MALE','$45000'),('MARY','LAMBERTH','FEMALE','$30000'),('VARALIE','VIKINGS','FEMALE','$35000')

SELECT * FROM tbl_Employee

SELECT * FROM tbl_Employee ORDER BY SALARY DESC

SELECT MAX(SALARY) 
FROM tbl_Employee 
WHERE SALARY < (SELECT MAX(SALARY) FROM tbl_Employee)


SELECT TOP 2 SALARY FROM 
(SELECT DISTINCT TOP 2 SALARY FROM tbl_Employee ORDER BY SALARY DESC) AS RESULT
ORDER BY SALARY

--SELECT SALARY,DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSEMARK FROM tbl_Employee

--WITH RESULT AS
--(
--	SELECT SALARY,DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSEMARK 
--	FROM tbl_Employee
--)
--SELECT TOP 1 SALARY 
--FROM RESULT
--WHERE RESULT.DENSEMARK = 1

SELECT SALARY FROM tbl_Employee ORDER BY SALARY DESC
GO

WITH RESULT AS
(
	SELECT SALARY, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSERANK
	FROM tbl_Employee
)
SELECT TOP 1 SALARY 
FROM RESULT
WHERE RESULT.DENSERANK = 1


-- NOT WORKING
WITH RESULT AS
(
	SELECT SALARY, ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS ROWNUMBER
	FROM tbl_Employee
)
SELECT SALARY 
FROM RESULT
WHERE RESULT.ROWNUMBER = 1