USE UAT

SELECT NAME,Gender,Salary,
FIRST_VALUE(NAME) OVER(ORDER BY SALARY) AS FIRSTVALUE
FROM Employees



SELECT NAME,Gender,Salary,
FIRST_VALUE(NAME) OVER(PARTITION BY GENDER ORDER BY SALARY) AS FIRSTVALUE
FROM Employees