--DETERMINISTIC
SELECT POWER(2,3) -- NON-DETERMINISTIC
SELECT SUM(2+2) --NON-DETERMINISTIC
SELECT GETDATE() --DETERMINISTIC
SELECT CURRENT_TIMESTAMP --DETERMINISTIC

SELECT RAND() --NON- DETERMINISTIC
SELECT RAND(1) --NON-DETERMINISTIC

SELECT * FROM tblEmployee

Alter FUNCTION FN_GETNAMEBYID(@ID INT)
RETURNS NVARCHAR(50)
with schemabinding 
AS
BEGIN
	RETURN(SELECT NAME FROM dbo.tblEmployee WHERE ID=@ID)
END

SELECT  DBO.FN_GETNAMEBYID(3)

drop table tblEmployee
