USE DBtest

CREATE TABLE LAPTOP
(
	LAPTOP_ID INT IDENTITY(1,1) PRIMARY KEY,
	LAPTOP_NAME NVARCHAR(250)
)
set IDENTITY_INSERT DBO.LAPTOP ON
INSERT INTO LAPTOP(LAPTOP_ID,LAPTOP_NAME) VALUES(1,'HP'),(2,'LENOVO'),(3,'DELL'),(4,'ASUS'),(5,'ACER'),(6,'TATA')
set IDENTITY_INSERT  DBO.LAPTOP OFF

SELECT * FROM DBO.LAPTOP

CREATE TABLE LAPTOP_USERNAME
(
  USER_ID INT IDENTITY(1,1),
  NAME NVARCHAR(250),
  EMAIL NVARCHAR(250),
  ADDRESS NVARCHAR(250),
  MOBILE NVARCHAR(250),
  COMPANY NVARCHAR(250),
  LAPTOP_ID INT FOREIGN KEY REFERENCES LAPTOP(LAPTOP_ID)
)

INSERT INTO DBO.LAPTOP_USERNAME(NAME,EMAIL,ADDRESS,MOBILE,COMPANY,LAPTOP_ID) VALUES('PRASAD','PRA@GMAIL.COM','889889476','JOGESHWARI','J&J',1)

SELECT * FROM DBO.LAPTOP_USERNAME

-----------------------------------------------------------------

CREATE TRIGGER DBO.TGR_LAPTOPUSER ON DBO.LAPTOP_USERNAME
AFTER DELETE 
AS
BEGIN 
	ROLLBACK TRAN
END

-----------------------------------------------------------------

DELETE FROM DBO.LAPTOP_USERNAME WHERE LAPTOP_ID = 1

--Msg 3609, Level 16, State 1, Line 37
--The transaction ended in the trigger. The batch has been aborted
