USE UAT

SELECT Name,Gender,Salary,
LAST_VALUE(NAME) OVER(ORDER BY SALARY) AS LASTVALUE
FROM Employees


SELECT Name,Gender,Salary,
LAST_VALUE(NAME) OVER(ORDER BY SALARY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LASTVALUE
FROM Employees


SELECT Name,Gender,Salary,
LAST_VALUE(NAME) OVER(PARTITION BY GENDER ORDER BY SALARY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LASTVALUE
FROM Employees