USE UAT

SELECT NAME,Gender,Salary,
LEAD(Salary) OVER(ORDER BY SALARY) AS [LEAD],
LAG(SALARY) OVER(ORDER BY SALARY) AS [LAG]
FROM Employees


SELECT NAME,Gender,Salary,
LEAD(Salary,2,-1) OVER(ORDER BY SALARY) AS [LEAD],
LAG(SALARY,1,-1) OVER(ORDER BY SALARY) AS [LAG]
FROM Employees



SELECT NAME,Gender,Salary,
LEAD(Salary,2,-1) OVER(PARTITION BY GENDER ORDER BY SALARY) AS [LEAD],
LAG(SALARY,1,-1) OVER(PARTITION BY GENDER ORDER BY SALARY) AS [LAG]
FROM Employees