use UAT
 

CREATE FUNCTION INLINE()
RETURNS TABLE
AS
	RETURN(SELECT * FROM tblEmployee)

SELECT * FROM INLINE() --HOW TO CALL INLINE FUNCION

CREATE FUNCTION MULTILINE()
RETURNS @TABLE TABLE (ID INT,NAME VARCHAR(20),GENDER VARCHAR(20),SALARY NVARCHAR(20))
AS
BEGIN
	INSERT INTO @TABLE
	SELECT ID,NAME,GENDER,SALARY FROM tblEmployee

	RETURN
END

SELECT * FROM MULTILINE()