Use UAT

SELECT NAME,Gender,Salary,
NTILE(2) OVER(ORDER BY SALARY)
FROM Employees


SELECT NAME,Gender,Salary,
NTILE(11) OVER(ORDER BY SALARY)
FROM Employees


SELECT NAME,Gender,Salary,
NTILE(3) OVER(PARTITION BY GENDER ORDER BY SALARY)
FROM Employees