SELECT ABS(-209.89)-- RETURN THE ABSOLUTE VALUE OF A NUMBER

SELECT ACOS(0.25) -- RETURN THE ARC COSINE OF A NUMBER

SELECT ASIN(0.25) -- RETURN THE ARC SINE OF THE NUMBER
SELECT ASIN(1)

SELECT ATAN(2.5)
