SELECT ASCII('HELLO') -- RETURN INTO CHAR VALUES IN INTEGER TYPE
SELECT ASCII('H')

SELECT CHAR(72) -- CONVERT INTO ASCII VALUE

SELECT CHARINDEX('L','HELLO') --RETURN POSSITION IF YOU TYPE L THAN YOU WILL 5 BECAUSE L ON 5 POSSINT IN THE HELLO

SELECT CONCAT('PRAVEEN ','KUMAR') -- ADD TO STRING TOGETHER 

SELECT 'PRAVEEN' + ' PRAJAPATI'

SELECT CONCAT_WS('-','WWW','PRAVEEN')-- NOT WORKING

SELECT DATALENGTH('HELLO DUNIA')

SELECT DIFFERENCE('HELLO', 'HELLO') -- NOT UNDERSTAND
SELECT SOUNDEX('HILLO') --NOT UNDERSTAND

--=====================================================================
DECLARE @DATE DATETIME = '12/10/1994' -- RETUTN DATE FROM DEFIND CONTREE
SELECT FORMAT(@DATE, 'D','en-US'),
	   FORMAT(@DATE, 'D' , 'no'),
	   FORMAT(@DATE,'D', 'ZU')
	   
--=====================================================================

SELECT LEFT('HELLO',35) -- THE LEFT FUNCTION EXTRATS A NUMBER OF CHARACTERS FROM A STRING(STARTING FROM LEFT)
SELECT RIGHT('HELLO',2) --THE RIGHT FUNCTION EXTRATS A NUMBER OF CHARACTERS FROM A STRING(STARTING FROM RIGHT)

SELECT LEN('HELLO') --RETURN LENGHT OF THE STRING

SELECT LOWER('HELLO') -- CONVERT THE TEXT TO LOWER CASE
SELECT UPPER('hello') -- CONVERT THE TEXT TO UPPER CASE

SELECT LTRIM('  HELLO') -- REMOVE SPACE FROM LEFT SIDE (MEANS REMOVE LEADING SPACE FROM A STRING)
SELECT RTRIM('HELLO  ') -- REMOVE SPACE FROM RIGHT SIDE (MEANS REMOVE LEADING SPACE FROM A STRING)

SELECT NCHAR(90) -- NCHAR RETURN THE UNICODE CHARACTER BASED ON THE NUMBER CODE.

SELECT PATINDEX('%EEN%', 'PRAVEEN')  -- PATINDEX FUNCTION RETURN THE POSSITION OF A PATTERN IN A STRING

SELECT QUOTENAME('ABCDEF') -- RETURN A UNICODE STRING WITH BRACKET DELIMINATERS(DEFAULT [])
SELECT QUOTENAME('AHTML','()') -- EXAMPLE

SELECT REPLACE('NAVEEN','N','M') -- REPLACE N WITH M

SELECT REPLICATE('HELLO ',2) -- REPLICATE USE FOR REPEAT A STRING A SPECIFIED NUMBER OF TIMES

SELECT REVERSE('HELLO WORLD') -- REVERSE A STRING A RETURN THE RESELT

SELECT SOUNDEX('HELLO'), SOUNDEX('HILLO')  -- NOT UNDERSTAND

SELECT SPACE(10) -- RETURN STRING WITH 10 SPACE

SELECT STR(185) -- RETURN A NUMBER AS STRING

SELECT STUFF('SQL Tutorial', 1, 3,'HTML') -- STUFF FUNCTION DELETE A PART OF STRING AND THEN INSERTS ANOTHER STRING, STARTING AT A SPECIFIED POSSITION 
SELECT STUFF('PRAVEEN PRAJAPATI',9,18,'KUMAR') -- STUFF FUNCTION DELETE A PART OF STRING AND THEN INSERTS ANOTHER STRING, STARTING AT A SPECIFIED POSSITION

SELECT SUBSTRING('HEELO',1,3) -- EXTRACT CHARACTER FROM A STRING, STARTING POSSITION 1
SELECT SUBSTRING('PRAVEEN',3,2) --EXAMPLE RETURN (AV)

SELECT TRANSLATE('MONDAY','MONDAY','SUNDAY') -- FUNCTION NOT WORKING

SELECT TRIM(' HELLO ')  --'TRIM' is not a recognized built-in function name

SELECT UNICODE('I') -- RETURN AN INTEGER VALUE (THE UNICODE VALUE) FOR THE FIRST CHARACTER OF THE INPUT EXPRESSION

SELECT UPPER('dear team kindly signoff attached document')




