

-- THIS IS LOCAL TEMPARARY TABLE.
--A LOCAL TEMPARY TABLE AUTOMATIC DROPED WHEN THE CONNECTION THAT HAS CREATED THE IT.
CREATE TABLE #TBL_TEMP 
(
	ID INT IDENTITY(1,1),
	NAME VARCHAR(50),
	EMAIL VARCHAR(50),
	MOBILE VARCHAR(50),
	ADDRESS VARCHAR(50)
)

INSERT INTO #TBL_TEMP(NAME,EMAIL,MOBILE,ADDRESS) VALUES('TEST_NAME','TEST_NAME@GMAIL.COM','23534455','JOGE')
INSERT INTO #TBL_TEMP(NAME,EMAIL,MOBILE,ADDRESS) VALUES('TINF_NAME','TINF_NAME@GMAIL.COM','2354455','BOGE')
INSERT INTO #TBL_TEMP(NAME,EMAIL,MOBILE,ADDRESS) VALUES('TSDF_NAME','TSDF_NAME@GMAIL.COM','2235455','FOGE')
INSERT INTO #TBL_TEMP(NAME,EMAIL,MOBILE,ADDRESS) VALUES('SDFH_NAME','SDFH_NAME@GMAIL.COM','2233455','KOGE')

SELECT * FROM #TBL_TEMP


-- THIS IS GLOBLE TEMPARARY TABLE.
-- ALIVE LAST CONNECTION
CREATE TABLE ##TBL_TEMP 
(
	ID INT IDENTITY(1,1),
	NAME VARCHAR(50),
	EMAIL VARCHAR(50),
	MOBILE VARCHAR(50),
	ADDRESS VARCHAR(50)
)

INSERT INTO ##TBL_TEMP(NAME,EMAIL,MOBILE,ADDRESS) VALUES('TEST_NAME','TEST_NAME@GMAIL.COM','23534455','JOGE')
INSERT INTO ##TBL_TEMP(NAME,EMAIL,MOBILE,ADDRESS) VALUES('TINF_NAME','TINF_NAME@GMAIL.COM','2354455','BOGE')
INSERT INTO ##TBL_TEMP(NAME,EMAIL,MOBILE,ADDRESS) VALUES('TSDF_NAME','TSDF_NAME@GMAIL.COM','2235455','FOGE')
INSERT INTO ##TBL_TEMP(NAME,EMAIL,MOBILE,ADDRESS) VALUES('SDFH_NAME','SDFH_NAME@GMAIL.COM','2233455','KOGE')

SELECT * FROM ##TBL_TEMP


CREATE PROC SPTEMP
AS
BEGIN
CREATE TABLE #SPTBL_TEMP 
(
	ID INT IDENTITY(1,1),
	NAME VARCHAR(50),
	EMAIL VARCHAR(50),
	MOBILE VARCHAR(50),
	ADDRESS VARCHAR(50)
)

INSERT INTO #TBL_TEMP(NAME,EMAIL,MOBILE,ADDRESS) VALUES('TEST_NAME','TEST_NAME@GMAIL.COM','23534455','JOGE')
INSERT INTO #TBL_TEMP(NAME,EMAIL,MOBILE,ADDRESS) VALUES('TINF_NAME','TINF_NAME@GMAIL.COM','2354455','BOGE')
INSERT INTO #TBL_TEMP(NAME,EMAIL,MOBILE,ADDRESS) VALUES('TSDF_NAME','TSDF_NAME@GMAIL.COM','2235455','FOGE')
INSERT INTO #TBL_TEMP(NAME,EMAIL,MOBILE,ADDRESS) VALUES('SDFH_NAME','SDFH_NAME@GMAIL.COM','2233455','KOGE')

SELECT * FROM #TBL_TEMP
END