


CREATE TABLE TBLEMPLOYEEAUDIT
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	AUDITDATA VARCHAR(1000)
)

CREATE TRIGGER TR_TBLEMPLOYEE_FORINSERT
ON TBLEMPLOYEE
FOR INSERT
AS
BEGIN
	DECLARE @ID INT
	SELECT @ID = ID FROM inserted

	INSERT INTO TBLEMPLOYEEAUDIT
	VALUES('NEW EMPLOYEE WITH ID = '+ CAST(@ID AS nvarchar(5)) +'IS ADDED AT'+ CAST(GETDATE() AS nvarchar(20)))
END

SELECT * FROM tblEmployee
SELECT * FROM TBLEMPLOYEEAUDIT

Insert into tblEmployee values (12,'Tan','FEMALE', 2300, '1', 3)

CREATE TRIGGER TR_TBLEMPLOYEE_FORDELETE
ON TBLEMPLOYEE
FOR DELETE
AS
BEGIN
	DECLARE @ID INT
	SELECT @ID = ID FROM deleted

	INSERT INTO TBLEMPLOYEEAUDIT
	VALUES('AN EXISTING EMPLOYEE WITH ID = ' + CAST(@ID AS nvarchar(5))+'IS DELETED AT' + CAST(GETDATE() AS NVARCHAR(20)))
END

DELETE FROM tblEmployee WHERE ID = 2