
SELECT TRY_CONVERT(INT, 'ACB') AS RESULT

SELECT TRY_CONVERT(INT, '99') AS RESULT

SELECT TRY_CONVERT(XML, 10) AS RESULT -- OCCURED ERROR


SELECT 
CASE WHEN TRY_CONVERT(INT, 'ABC') IS NULL
	THEN 'CONVERSION FAIL'
	ELSE 'CONVERSION SUCCESSFULL'
END AS RESULT



SELECT 
CASE WHEN TRY_CONVERT(INT, '99') IS NULL
	THEN 'CONVERSION FAIL'
	ELSE 'CONVERSION SUCCESSFULL'
END AS RESULT



SELECT IIF(TRY_CONVERT(INT, 'ABC')IS NULL, 'CONVERSION FAIL','CONVERSION SUCCESSFULL')


SELECT IIF(TRY_CONVERT(INT, '99')IS NULL, 'CONVERSION FAIL','CONVERSION SUCCESSFULL')


SELECT CONVERT(INT, 'ABC') AS RESULT

SELECT TRY_CONVERT(INT, 'ABC') AS RESULT