USE UAT

SELECT NAME, Gender,Salary,
SUM(Salary) AS SUMSALARY
FROM Employees
GROUP BY NAME,GENDER,Salary


SELECT Gender,
SUM(Salary) AS SUMSALARY
FROM Employees
GROUP BY GENDER


SELECT NAME, Gender,Salary,
SUM(Salary) OVER(ORDER BY sALARY) AS SUMSALARY,
COUNT(Salary) OVER(ORDER BY GENDER) AS COUNTSALARY,
AVG(Salary) OVER(ORDER BY GENDER) AS AVGSALARY
FROM Employees


SELECT DISTINCT Salary,
COUNT(Salary) OVER(PARTITION BY SALARY ORDER BY SALARY ) AS COUNTSALARY
FROM Employees


SELECT Salary,
COUNT(Salary) AS COUNTSALARY
FROM Employees
GROUP BY Salary


SELECT NAME, Gender,Salary,
SUM(Salary) OVER(ORDER BY SALARY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS SUMSALARY,
COUNT(Salary) OVER(ORDER BY SALARY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS COUNTSALARY,
AVG(Salary) OVER(ORDER BY SALARY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS AVGSALARY
FROM Employees



--In SQL Server we have different categories of window functions
SELECT NAME, Gender,Salary,
SUM(Salary) OVER(PARTITION BY GENDER ORDER BY SALARY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS SUMSALARY,
COUNT(Salary) OVER(PARTITION BY GENDER ORDER BY SALARY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS COUNTSALARY,
AVG(Salary) OVER(PARTITION BY GENDER ORDER BY SALARY ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS AVGSALARY
FROM Employees



